FROM python:3.14-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install uv --quiet

COPY pyproject.toml ./

COPY app/ ./app/
RUN uv sync --no-dev


CMD ["sh", "-c", "uv run python -m app.broker.consumer"]